### PR TITLE
Update virtual.py

### PR DESCRIPTION
**Pull request by shivambitm**
Solving issue - https://github.com/My-Personal-HUB/AI_Jarvis/issues/4

### CODE REVIEW

**Review by ayushii18 — CHANGES_REQUESTED** [review]
@shivamkumar0611 this pull request is conflicting with the original code

**Comment by shivambitm** [comment]
> @shivamkumar0611 this pull request is conflicting with the original code

okay let me check it

**Comment by shivambitm** [comment]
> @shivamkumar0611 this pull request is conflicting with the original code

**_### _solved the conflict in just 15 minutes @ayushii18__** 
saved_jarvis

**Comment by ayushii18** [comment]
> > @shivamkumar0611 this pull request is conflicting with the original code
> 
> **_### _solved the conflict in just 15 minutes @ayushii18__**
> saved_jarvis

Amazing working with you 
I'm merging this last pull request. Thanks again @shivamkumar0611 
Not only you solved the issue and conflict but also you completed the project 
Will surely meet in our next project with you all .

**Comment by shivambitm** [comment]
> > > @shivamkumar0611 this pull request is conflicting with the original code
> > 
> > 
> > **_### _solved the conflict in just 15 minutes @ayushii18__**
> > saved_jarvis
> 
> Amazing working with you
> I'm merging this last pull request. Thanks again @shivamkumar0611
> Not only you solved the issue and conflict but also you completed the project
> Will surely meet in our next project with you all .

Okay then I'm resolving this comment and successfully closing the project.

**Comment by ayushii18** [comment]
Thanks to all the contributors @shivamkumar0611 @ayushii18 @sauravmandal255 @rohansahana6 @santosh-sudo 
Me including

**Pull request merged**
